version: "3.8"
services:
  client:
    build: ./client
    container_name: motonreel_client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
  
  server:
    build: ./server
    container_name: motonreel_server
    ports:
      - '9000:9000'
    volumes:
      - ./server:/usr/src/app

